#! /usr/bin/env python3
#
# post-receive hook to trigger the repository webhook.
#
# This file is symlinked to every repo as hooks/post-receive.
#
# The webhook url is stored at hooks/webhook.txt file in the repo.
# Only one webhook is supported per repo.
#
from pathlib import Path
from urllib.request import urlopen, Request
import json
import sys

def get_webhook_url():
    """The webhook is stored in the webhook.txt file relative to this script.
    """
    hook = Path(__file__).parent / "webhook.txt"
    if hook.exists():
        return hook.read_text()

def trigger_webhook(url):
    payload = {

    }
    req = Request(url,
                  data=json.dumps(payload).encode('utf-8'),
                  headers={"Content-type": "application/json"})

    try:
        response = urlopen(req)
        d = response.read().decode('utf-8')
        print(d)
    except Exception as e:
        print(f"\nFailed to trigger webhook ({e})\n", file=sys.stderr)

def main():
    url = get_webhook_url()
    if url:
        trigger_webhook(url)

if __name__ == "__main__":
    main()