name: deploy-staging

on:
  push:
    branches:
      - main

env:
  CAPSTONE_USER = capstone
  CAPSTONE_HOST = capstone-staging.pipal.in

jobs:
  build:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo $PIPAL_BOT_SSH_KEY > pipalbot.key
          ssh -i ./pipalbot.key $CAPSTONE_USER@$CAPSTONE_HOST bash -c 'cd capstone; git pull && venv/bin/python -m pip install -U -r requirements.txt && venv/bin/python run.py --migrate && sudo supervisorctl restart capstone'
