name: Run Tests
on:
  push:
    branches:
      - main

env:
  TEST_DATABASE_URL: "postgres://postgres:postgres@localhost/postgres"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r dev-requirements.txt -r requirements.txt
    - name: Run tests
      run: ./runtests.sh

  deploy-staging:
    runs-on: ubuntu-latest
    needs: run-tests
    env:
      CAPSTONE_USER: capstone
      CAPSTONE_HOST: capstone-staging.pipal.in
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo $PIPAL_BOT_SSH_KEY > pipalbot.key
          ssh -i ./pipalbot.key $CAPSTONE_USER@$CAPSTONE_HOST bash -c 'cd capstone; git pull && venv/bin/python -m pip install -U -r requirements.txt && venv/bin/python run.py --migrate && sudo supervisorctl restart capstone'
