name: Test and Deploy

on:
  push:
    branches:
      - main
      - '**-cicd'

env:
  TEST_DATABASE_URL: "postgres://postgres:postgres@localhost/postgres"
  NOMAD_VERSION: "1.5.2"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r dev-requirements.txt -r requirements.txt
    - name: Install apt dependencies
      run: sudo apt-get install -y zip unzip
    - name: Setup git
      run: |
        git config --global user.name "capstone-pipal"
        git config --global user.email "capstone@pipal.in.test"
    - name: Install Nomad
      run: |
        wget -O /tmp/nomad.zip https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip
        sudo unzip /tmp/nomad.zip -d /usr/local/bin/
        nomad version
    - name: Start Nomad
      run: |
        ./nomad-scripts/nomad.sh &
    - name: Wait for Nomad
      run: |
        until nomad status; do sleep 2; done
    - name: Run tests
      run: ./runtests.sh

  deploy-staging:
    runs-on: ubuntu-latest
    env:
      NOMAD_VAR_gitto_api_token: ${{ secrets.CAPSTONE_STAGING_GITTO_API_TOKEN }}
      NOMAD_VAR_gitto_host: git.capstone-staging.pipal.in
    needs: run-tests
    steps:
      - name: Deploy to staging
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: capstone-staging.pipal.in
          username: capstone
          key: ${{ secrets.PIPAL_BOT_SSH_KEY }}
          script: |
            bash -c 'cd capstone; git pull && venv/bin/python -m pip install -U -r requirements.txt && sudo apt-get install -y zip unzip && venv/bin/python run.py --migrate && ./nomad-scripts/start-jobs.sh && sudo supervisorctl restart capstone capstone-tasks && ./runner/build-and-replace-docker-image.sh'
